branches:
  - master
  - name: release-+([0-9]).+([0-9]).+([0-9])
    prerelease: beta
ci: true
tagFormat: ${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
        - type: feat
          section: "Features"
          hidden: false
        - type: fix
          section: "Fixes"
          hidden: false
        - type: docs
          section: "Other changes"
          hidden: false
        - type: style
          section: "Other changes"
          hidden: false
        - type: refactor
          section: "Other changes"
          hidden: false
        - type: perf
          section: "Fixes"
          hidden: false
        - type: test
          section: "Other changes"
          hidden: false
        - type: ci
          section: "Other changes"
          hidden: false
        - type: chore
          hidden: true
  - - "@semantic-release/exec"
    - generateNotesCmd: sh prepare_release.sh ${nextRelease.version} ${branch.name} "${nextRelease.notes}" ${lastRelease.version} ${Date.now()}
  - - "@semantic-release/github"
    - assets:
      - path: "multi.vsix"
        label: "hlasm-language-support-${nextRelease.version}.vsix"
        name: "hlasm-language-support-${nextRelease.version}.vsix"
      - path: "alpine.vsix"
        label: "hlasm-language-support-${nextRelease.version}-alpine.vsix"
        name: "hlasm-language-support-${nextRelease.version}-alpine.vsix"
  
