#!/usr/bin/env bash
set -e
cmake -A ARM64 -DCMAKE_SYSTEM_NAME="Windows" -DCMAKE_SYSTEM_VERSION="10" -DCMAKE_BUILD_TYPE=Release -DDISCOVER_TESTS=Off -DBUILD_VSIX=Off -DUSE_PRE_GENERATED_GRAMMAR="generated_parser" ../
