#
# Copyright (c) 2019 Broadcom.
# The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Broadcom, Inc. - initial API and implementation
#

name: Check license headers
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
jobs:
  
  clang:
      name: Check license headers
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v1
      - name: Check license headers
        run: |
          chmod +x cmake/check_license.sh
          cmake/check_license.sh

